//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("EMV Card Browser")]
[assembly: AssemblyDescription("A tool to read EMV smartcard files and display the results. This program uses cod" +
    "e derived from the Mono.Security.ASN1 class.")]
[assembly: AssemblyCompany("Nic Bedford")]
[assembly: AssemblyProduct("CardBrowser")]
[assembly: AssemblyCopyright("Copyright © 2009 - 2010")]
[assembly: AssemblyVersion("0.0.1.81")]
[assembly: AssemblyFileVersion("0.0.1.81")]


